### ISSUE TITLE
Install script unable to find releases

### ISSUE THREAD

**Issue by igor-v-seed** [anchore/grype#1103] opened 2023-01-28 02:14 UTC
**What happened**: 
Running the install script as such: `curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin` gives an error 
`[info] checking github for the current release tag
[error] unable to find tag=''
[error] do not specify a version or select a valid version from https://github.com/anchore/grype/releases`

This also happens if you specify a tag:
`curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin v0.56.0
[info] checking github for release tag='v0.56.0'
[error] unable to find tag=''
[error] do not specify a version or select a valid version from https://github.com/anchore/grype/releases`

**What you expected to happen**: Grype to be installed. 

**How to reproduce it (as minimally and precisely as possible)**: Run the install script exactly as in the read me.

**Anything else we need to know?**: Doesn't work on multiple OSes. The same issue occurs with the syft install script

**Environment**:
- Output of `grype version`: 
- OS (e.g: `cat /etc/os-release` or similar): macOS, RHEL 8.6

**Comment by kzantow** [comment] 2023-01-28 15:10
Hi @igor-v-seed I've just tried this out for macOS and Linux and it seems to be working fine for me, could you retry?

NOTE I saw a failure yesterday where https://github.com/anchore/grype/releases/download/v0.56.0/grype_0.56.0_linux_arm64.deb was returning 403 for some reason, but seems to be fine now.

**Comment by kzantow** [comment] 2023-01-28 15:20
Hi @igor-v-seed I'm going to close this as a duplicate of #1102 -- please watch and/or comment there if you continue to have issues, thanks!

**Closed by kzantow** 2023-01-28 15:20 UTC
Labels: bug, duplicate
