### ISSUE TITLE
Getting Error while installing Grype

### ISSUE THREAD

**Issue by Tamizh-Thiru** [anchore/grype#1780] opened 2024-04-03 04:14 UTC
**What happened**: While installing the grype getting the Error
**[error] received HTTP status=000 for url='https://github.com/anchore/grype/releases/latest'
[error] unable to find tag=''
[error] do not specify a version or select a valid version from https://github.com/anchore/grype/releases**

 I tried with three different way to install grype

1. curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin 0.15.0
2. 
3. curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
4. 
5. and 
6. 
7. git clone https://github.com/anchore/grype.git
8. executed ./install.sh

getting the error for all 3 ways, didn't get any idea

**Comment by tgerla** [comment] 2024-04-03 12:17
Hi @Tamizh-Thiru, I just tested out a couple of installs on my machine and I am unable to reproduce the problem. Do you have a firewall or proxy in between you and GitHub? It is possible that there was a networking problem that is now resolved? You can also add "-d" to the install.sh command for additional debug logging.

**Comment by tgerla** [comment] 2024-04-18 18:30
Hi, we'll go ahead and close this issue but if you need more help, just let us know. Thanks.

**Closed by tgerla** 2024-04-18 18:30 UTC
Labels: bug
