### ISSUE TITLE
Restrict output to a given severity level

### ISSUE THREAD

**Issue by Itxaka** [anchore/grype#2117] opened 2024-09-16 13:03 UTC
**What would you like to be added**:
Instead of a flag like `--fail-on SEVERITY` a new flag for output called something like `--severity SEVERITY1,SEVERITY2` could eb added to produce only results that match eh given severities

**Why is this needed**:
we scan several distros and upload them to github security actions. This results in a huge file with a lot of reports in which we are not really interested (> 5900 entries). It would be nice to only output those of a given severity and above so we can have nicer smaller reports of the severities.

**Additional context**:

**Comment by Itxaka** [comment] 2024-09-16 13:06
maybe the `ignore` config key can be expanded to also get a severity?

**Comment by willmurphyscode** [comment] 2024-09-30 14:18
Thanks for the request! We already plan to do this.

Closing as duplicate of https://github.com/anchore/grype/issues/2006

**Closed by willmurphyscode** 2024-09-30 14:18 UTC
Labels: enhancement
